### ISSUE TITLE
Taskbar icon missing in 2.9.0-26

### ISSUE THREAD

**Issue by rarog** [portapps/slack-portable#12]
That's a very small and unimportant and cosmetic only bug, but a bug.

![2017-11-22_08h47_08](https://user-images.githubusercontent.com/2520875/33116461-183ca858-cf65-11e7-8bdd-37a403f84a7a.png)

**Comment by crazy-max** [comment]
@rarog Can you check the latest release ?

**Comment by rarog** [comment]
3.0.0-28 still has the same problem.

**Comment by crazy-max** [comment]
Ok I will take a look on this

**Comment by crazy-max** [comment]
I think i have found the issue.
Can you copy the file `app/app.ico` to `app/app-win10.ico`.

Thanks.

**Comment by rarog** [comment]
Unfortunately that didn't solve it for me, it's still blank.

**Comment by crazy-max** [comment]
Ok,

Can you post your slack-portable.log please ?
And also, can you test from a fresh installation ?

Thanks

**Comment by rarog** [comment]
Same result.

I did a fresh install and copied `app.ico` to `app-win10.ico` before the first start.

The log doesn't look suspicious:

```
INFO : 2017/12/18 09:12:52.944983 main.go:78: --------
INFO : 2017/12/18 09:12:52.985004 main.go:79: Starting Slack...
INFO : 2017/12/18 09:12:52.985004 main.go:80: Current path: C:\slack-portable
INFO : 2017/12/18 09:12:52.985004 main.go:85: Lookup app folder in: C:\slack-portable\app
INFO : 2017/12/18 09:12:52.986005 main.go:89: Electron app folder found: app-3.0.0
INFO : 2017/12/18 09:12:52.986005 main.go:178: Create folder C:\slack-portable\data\AppData\Roaming\Slack...
INFO : 2017/12/18 09:12:52.986993 main.go:25: Roaming path: C:\slack-portable\data\AppData\Roaming\Slack
INFO : 2017/12/18 09:12:52.986993 main.go:178: Create folder C:\slack-portable\downloads...
INFO : 2017/12/18 09:12:52.989029 main.go:35: Update Slack settings...
ERROR: 2017/12/18 09:12:52.990003 main.go:59: Slack settings not found in C:\slack-portable\data\AppData\Roaming\Slack\storage\slack-settings
INFO : 2017/12/18 09:12:52.990003 main.go:156: Process: C:\slack-portable\app\Slack.exe
INFO : 2017/12/18 09:12:52.990003 main.go:157: Args: 
INFO : 2017/12/18 09:12:52.990003 main.go:158: Working dir: C:\slack-portable\app\app-3.0.0
INFO : 2017/12/18 09:12:52.990003 main.go:159: Data path: C:\slack-portable\data
INFO : 2017/12/18 09:12:52.990003 main.go:161: Launch Slack...
INFO : 2017/12/18 09:12:52.990003 main.go:168: Exec C:\slack-portable\app\Slack.exe 

Creating Slack Application
```

**Comment by crazy-max** [comment]
Hi @rarog,

On release 3.0.3 i've the taskbar icon, can you check on your computer ?
Btw, what is your OS (Win 7 / 8.1 / 10) ?

![image](https://user-images.githubusercontent.com/1951866/34902836-19adf0ce-f824-11e7-9450-6cafd6a04f86.png)

**Comment by rarog** [comment]
I'm on 3.0.5 and it's back for me, so thx for solving! 👍
