### ISSUE TITLE
Request: option to keep roamingPath in %USERPROFILE%

### ISSUE THREAD

**Issue by srliao** [portapps/slack-portable#14]
Would be nice to add an option maybe via a config file to use `%USERPROFILE` instead of `Papp.DataPath` on line 24 `roamingPath := CreateFolder(PathJoin(Papp.DataPath, "AppData", "Roaming", "Slack"))` Or better yet, use `%APPDATA%\Slack`

I think (not sure - hopefully) this would allow Slack to behave more like a normal app that can be installed on one computer in the C drive somewhere and used by multiple users at the same time.

Here is the primary use case I am thinking of: https://www.reddit.com/r/Citrix/comments/6rkno0/slack_on_xendesktop/

**Comment by crazy-max** [comment]
Use on `%APPDATA%\Slack` is the default behavior of the official Slack setup. If we put this value, we lost the portable behavior included by slack-portable.
