### ISSUE TITLE
External apps are opening with wrong AppData folder

### ISSUE THREAD

**Issue by af4jm** [portapps/slack-portable#15]
Clicked a link in one of my Slack channels and instead of getting a new tab in my open browser window, I got an entirely new window, and it had none of my settings.  After a little digging I found a browser profile folder under AppData\Roaming\portapps\slack-portable\data, a folder which should have data ONLY for the portable app being run, NOT for any non-portable apps started from the portable app.  I've never seen that type of trojan-like behavior from a portable app before.

**Comment by crazy-max** [comment]
Can you follow the [SUPPORT instructions](https://github.com/portapps/slack-portable/blob/master/.github/SUPPORT.md) please ? Thanks.
