### ISSUE TITLE
Portable slack can't be run from a central share

### ISSUE THREAD

**Issue by mar1ged** [portapps/slack-portable#17]
We want to provide the portable Slack app from a (write-protected) network share to multiple users. Currently this fails because of two reasons:

- all users use the same directory which leads to sharing of personal data
- user directories can't be created when run from write protected media

Is there a way to tell the portable app where to store it's files ? Being able to specify `%USERPROFILE%` or `%LOCALAPPDATA%` would solve my problem.

I have seen a similar [issue](https://github.com/portapps/slack-portable/issues/13)  but didn't find a solution to my problem

**Comment by crazy-max** [comment]
@mar1ged Ok what you said is you want the binaries on a network share and data on the local drive ? If it's the case this is related to portapps/portapps#28.

**Comment by mar1ged** [comment]
Yes, this is related but still different.
 I would like to store `data`, `log`  and `downloads` on a local drive and run the "launcher" of the app _and_ all binaries that are stored in `app` from the network drive.
This is because we have a strict policy what can be stored and executed locally: I will not be able to download a binary locally and execute it from there. But the network drive is monitored and executables are whitelisted and execution is possible. Because of this no writes must happen to the network drive, it is write protected.

I've had a look at your [commit](https://github.com/portapps/portapps/commit/3595876418b283cfcbc261b9dc20aa68a333cc63). With my limited Go knowledge I would say that when you do the same for the `DataPath` and the `RootPath` (which seems to control where logs are stored) and build the Slack portable app anew this would solve my problem.

**Comment by crazy-max** [comment]
@mar1ged `app` binaries can already be stored on a different location using the YAML configuration file. See https://portapps.io/doc/configuration/ (`common` section and `app_path`)
Only data, log and downloads will be stored locally.

**Comment by mar1ged** [comment]
Sorry, but I think I don't get you. My point is that I can not put the wrapper locally (this is a limitation set by the company I work for). Besides that I failed to configure this.

I tried to mimic this locally:

```
c:
cd \temp
mkdir attempt
cd attempt
mkdir local
mkdir share
cd share
wget https://portapps.io/download/slack-portable-win64-3.4.1-21.7z
7z x slack-portable-win64-3.4.1-21.7z
echo. common:>slack-portable.yml
echo.   app_path: C:\temp\attempt\local
slack-portable
timeout /t 60
if exist C:\temp\attempt\share\data echo Failed!
if exist C:\temp\attempt\local\data echo Success!

```
The output is `Failed!`

This doesn't work they way I would need it to: wrapper, app binaries and all data are stored in the same directory.

What I would need to do is separate _all_ binaries (including the wrapper) from  dynamic data. Talking in cmdline this would be:

```
s:
cd \
mkdir slack
cd slack
wget https://portapps.io/download/slack-portable-win64-3.4.1-21.7z
7z x slack-portable-win64-3.4.1-21.7z
del *.7z
echo. common: > slack-portable.yml
echo.   data_path: C:\users\username\AppData\Roaming\slack\data>> slack-portable.yml
echo.   log_path: C:\users\username\AppData\Roaming\slack\log>> slack-portable.yml
echo.   dl_path: C:\users\username\AppData\Roaming\slack\downloads>> slack-portable.yml

```

(S: is the network share I as administrator would have write access to, regular users don't have this permission)

**Comment by crazy-max** [comment]
Okay, I understand better now. I will see if it is possible to do that.

**Comment by mar1ged** [comment]
I just failed to find this issue from the list (didn't follow an external link) would you mind opening it again ?

**Comment by crazy-max** [comment]
After study, this improvement is not possible because it defeats the portable purpose.

Unlike portapps/portapps#28, this could also cause unexpected behaviour because the wrapper is strongly linked to its configuration file (and logs) and so cannot be shared.

**Comment by mar1ged** [comment]
OK, it's your project, so you decide ;-)

But I don't yet understand. The wrapper would be started by several people from the same location. Because they start the wrapper on different computers each user has a process of its own. Each instance of the wrapper reads the same config file, creating logs, download and other files on the computer of the respective user. Only the binaries from the app folder are shared, but again each in a process of its own.

Think of the network share as a big USB stick, shared by many people, but writing its data to a second personal USB stick ;-)

**Comment by crazy-max** [comment]
> ...started by several people from the same location.

This is the cause of the problem that would result in a locked log file because it would also be shared between users (`.\logs\*.log`). Also, as YAML configuration file must be in the same directory as the wrapper, each user cannot have his own configuration. For example, if user A has his network drive on U: and user B on V: the configuration cannot be applied for both.

**Comment by mar1ged** [comment]
In our scenario all users have the same network share with the same drive letter and unc path. And because all user files (logs included) are stored locally there won't be any conflicts or locked files.
I understand that our scenario differs a lot from the usual portable app approach. But if there would be support for settings to move logs, downloads, ... in the yaml we could make it work
